name: Index issues from configured GitHub repositories

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  call_api_job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js and NPM
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
          npm install axios
        working-directory: ${{ github.workspace }}

      - name: Run JavaScript File
        id: fetchIssues
        run: |
          node ./content/issues/fetchIssues.js > ./content/issues/issues.json
          cp ./content/issues/issues.json ./content/issues/issues.json.res

      - name: Push into Git
        run: |-
          if ! diff -q ./content/issues/issues.json{,.res} > /dev/null
          then
            git config --global user.email "bot@ark-builders.dev"
            git config --global user.name "ARK Builders Bot"
            git add ./content/issues/issues.json
            git commit -m "Indexing GitHub issues"
            git push
          fi
